spring.datasource.url=jdbc:postgresql://localhost:5433/academia_db
spring.datasource.username=academia_user
spring.datasource.password=academia_pass_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true